# Configuration for the OpenAPI generation tool
additionalProperties:
  generateSourceCodeOnly: true
  packageName: "tl_pax8"
globalProperties:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false
inputSpec: spec/pax8.json
outputDir: src
generatorName: python
